print("My name is keerthana")
print("I am 24 years old")
print("I am from Thoothukudi")
print("I am completed Master's degree in Data Science")
print("My Strength is hardworking and Qucik Learner")
print("My weakness is overthinking")
print("My hobbies are reading books and listening to music")
print("My goal is to become a Data Scientist in a MNC company")
print("Thank you!")