a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Square of first number:",a**2)
print("cube of first number:",a**3)
print("Average of three numbers:",a+(b+c)/3)
print("\nBefore swapping:")
print("a =", a)
print("b =", b)
print("c =", c)
print("\nAfter swapping:")
print("a =", b)
print("b =", c)
print("c =", a)
print("datatype of a:",type(a))
d=int(input("Enter integer value:"))
e=float(input("Enter float value:"))
print("Addition of integer and float:",d+e)
print("datatype after addition:",type(d+e))
print("Comparison Operators:")
print("a is greater than b:",a>b)
print("a is equal or not equal to b:",a!=b)
mark1= int(input("Enter first number:"))
mark2= int(input("Enter second number:"))
mark3= int(input("Enter third number:"))
mark4= int(input("Enter fourth number:"))
mark5= int(input("Enter fifth number:"))
average_marks= (mark1+mark2+mark3+mark4+mark5)/5
print("Average marks:",average_marks)
hours=float(input("Enter hours worked:"))
minutes = hours * 60
print(f"{hours} hour(s) = {minutes} minute(s)")
principal = float(input("Enter Principal Amount (P): "))
rate = float(input("Enter Rate of Interest (R): "))
time = float(input("Enter Time in Years (T): "))
simple_interest = (principal * rate * time) / 100
print(f"\nSimple Interest = (P * R * T) / 100 = {simple_interest}")
length = float(input("Enter length of rectangle: "))
breadth = float(input("Enter breadth of rectangle: "))
area = length * breadth
print(f"\nArea of Rectangle = {area}")
num = float(input("Enter a number: "))
print("Is the number greater than 0?", num > 0)
print("Is the number less than 0?", num < 0)
print("Is the number equal to 0?", num == 0)
cost = float(input("Enter cost of one item: "))
quantity = int(input("Enter number of items: "))
total = cost * quantity
print("Total Cost =", total)
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("Addition =", num1 + num2)
print("Subtraction =", num1 - num2)
print("Multiplication =", num1 * num2)
print("Division =", num1 / num2)